version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: unless-stopped
    container_name: test-db
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - 2345:5432